/**
 * Wisp — generated by Wisp
 *
 * 1. Discord Developer Portal → New Application → Bot
 * 2. Enable MESSAGE CONTENT INTENT
 * 3. Copy the bot token
 * 4. OAuth2 URL Generator → scopes: bot, applications.commands
 * 5. npm i discord.js
 * 6. DISCORD_TOKEN=... node bot.js
 */
import {
  Client,
  GatewayIntentBits,
  EmbedBuilder,
  SlashCommandBuilder,
  REST,
  Routes,
  PermissionFlagsBits,
} from "discord.js";

const TOKEN = process.env.DISCORD_TOKEN;
const PREFIX = "!";
const BANNED = ["scam","nitro free","free nitro"];
const xp = new Map();
const levels = new Map();
const queue = new Map();

if (!TOKEN) {
  console.error("Set DISCORD_TOKEN");
  process.exit(1);
}

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
  ],
});

function embed(description, title) {
  const e = new EmbedBuilder().setColor(0x5eead4).setDescription(description);
  if (title) e.setTitle(title);
  return e;
}

const commands = [
    new SlashCommandBuilder().setName("ping").setDescription("Check if the bot is awake."),
    new SlashCommandBuilder().setName("help").setDescription("List every enabled command."),
    new SlashCommandBuilder().setName("userinfo").setDescription("Show a member card.").addStringOption(o => o.setName("member").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("serverinfo").setDescription("Show this server at a glance."),
    new SlashCommandBuilder().setName("say").setDescription("Make the bot speak.").addStringOption(o => o.setName("text").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("8ball").setDescription("Ask a yes or no question.").addStringOption(o => o.setName("question").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("joke").setDescription("A short programming joke."),
    new SlashCommandBuilder().setName("poll").setDescription("Start a yes/no poll.").addStringOption(o => o.setName("question").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("rank").setDescription("Show your level and XP."),
    new SlashCommandBuilder().setName("play").setDescription("Queue a track.").addStringOption(o => o.setName("song").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("skip").setDescription("Skip the current track."),
    new SlashCommandBuilder().setName("queue").setDescription("Show the music queue."),
    new SlashCommandBuilder().setName("np").setDescription("What is playing right now."),
    new SlashCommandBuilder().setName("ban").setDescription("Ban a member (simulated).").addStringOption(o => o.setName("member").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("kick").setDescription("Kick a member (simulated).").addStringOption(o => o.setName("member").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("timeout").setDescription("Timeout a member (simulated).").addStringOption(o => o.setName("member").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("warn").setDescription("Warn a member.").addStringOption(o => o.setName("member").setDescription("Argument").setRequired(false)),
    new SlashCommandBuilder().setName("purge").setDescription("Clear recent messages (simulated).").addStringOption(o => o.setName("count").setDescription("Argument").setRequired(false))
].map(c => c.toJSON());

client.once("ready", async () => {
  console.log("Logged in as " + client.user.tag);
  client.user.setPresence({
    status: "online",
    activities: [{ name: "the harbor", type: 3 }],
  });
  const rest = new REST({ version: "10" }).setToken(TOKEN);
  await rest.put(Routes.applicationCommands(client.user.id), { body: commands });
});

client.on("guildMemberAdd", async (member) => {
  const ch = member.guild.systemChannel;
  const text = "Welcome {user} to **{server}**. You are member #{count}. Say /help to meet me."
    .replaceAll("{user}", "<@" + member.id + ">")
    .replaceAll("{username}", member.user.username)
    .replaceAll("{server}", member.guild.name)
    .replaceAll("{count}", String(member.guild.memberCount))
    .replaceAll("{prefix}", PREFIX)
    .replaceAll("{bot}", "Wisp");
  if (ch) await ch.send({ embeds: [embed(text, "Welcome")] });

});

client.on("messageCreate", async (message) => {
  if (message.author.bot) return;

  const lower = message.content.toLowerCase();
  if (BANNED.some((w) => w && lower.includes(w)) || /discord\.gg\/\w+/i.test(message.content)) {
    await message.delete().catch(() => {});
    await message.channel.send({ embeds: [embed("That message was blocked by automod. Keep the harbor clean.", "Automod")] });
    return;
  }


  const id = message.author.id;
  const cur = (xp.get(id) || 0) + 15 + Math.floor(Math.random() * 11);
  xp.set(id, cur);
  const lvl = levels.get(id) || 1;
  if (cur >= 80 * lvl) {
    levels.set(id, lvl + 1);
    xp.set(id, cur - 80 * lvl);
    await message.channel.send("**" + message.author.username + "** reached **level " + (lvl + 1) + "**.");
  }


  if (!message.content.startsWith(PREFIX)) return;
  const [name, ...rest] = message.content.slice(PREFIX.length).trim().split(/\s+/);
  await handleCommand(message, (name || "").toLowerCase(), rest.join(" "));
});

client.on("interactionCreate", async (interaction) => {
  if (!interaction.isChatInputCommand()) return;
  const args = interaction.options.data.map(o => o.value).filter(Boolean).join(" ");
  await handleInteraction(interaction, interaction.commandName, args);
});

async function handleInteraction(interaction, name, args) {
  switch (name) {
    case "ping":
      await interaction.reply({ embeds: [embed("Heartbeat **" + interaction.client.ws.ping + "ms**.", "Pong")] });
      break;
    case "help":
      await interaction.reply({
        embeds: [embed("`/ping` — Check if the bot is awake.\\n`/help` — List every enabled command.\\n`/userinfo` — Show a member card.\\n`/serverinfo` — Show this server at a glance.\\n`/say` — Make the bot speak.\\n`/8ball` — Ask a yes or no question.\\n`/joke` — A short programming joke.\\n`/poll` — Start a yes/no poll.\\n`/rank` — Show your level and XP.\\n`/play` — Queue a track.\\n`/skip` — Skip the current track.\\n`/queue` — Show the music queue.\\n`/np` — What is playing right now.\\n`/ban` — Ban a member (simulated).\\n`/kick` — Kick a member (simulated).\\n`/timeout` — Timeout a member (simulated).\\n`/warn` — Warn a member.\\n`/purge` — Clear recent messages (simulated).", "Wisp commands")],
      });
      break;
    case "say":
      await interaction.reply({ content: args || "…", allowedMentions: { parse: [] } });
      break;
    case "joke": {
      const jokes = ["Why do programmers prefer dark mode? Light attracts bugs.","A SQL query walks into a bar and asks: may I join you?"];
      await interaction.reply(jokes[Math.floor(Math.random() * jokes.length)]);
      break;
    }
    case "8ball":
      await interaction.reply({ embeds: [embed(["Yes.", "No.", "Ask again later.", "Signs point to yes."][Math.floor(Math.random()*4)], "8-ball")] });
      break;
    case "rank":
      await interaction.reply({ embeds: [embed("Level " + (levels.get(interaction.user.id) || 1) + " · " + (xp.get(interaction.user.id) || 0) + " XP", interaction.user.username)] });
      break;
    case "play":
      await interaction.reply({ embeds: [embed(args || "Untitled track", "Now playing")] });
      break;
    case "skip":
      await interaction.reply({ embeds: [embed("Skipped.", "Queue")] });
      break;
    case "queue":
    case "np":
      await interaction.reply({ embeds: [embed("Check your voice channel.", "Music")] });
      break;
    case "userinfo":
      await interaction.reply({ embeds: [embed("ID " + interaction.user.id, interaction.user.username)] });
      break;
    case "serverinfo":
      await interaction.reply({ embeds: [embed(interaction.guild ? interaction.guild.name : "DM", "Server")] });
      break;
    case "poll":
      {
        const msg = await interaction.reply({ embeds: [embed(args || "Yes or no?", "Poll")], fetchReply: true });
        await msg.react("✅");
        await msg.react("❌");
      }
      break;
    case "ban":
    case "kick":
    case "timeout":
    case "warn":
    case "purge":
      if (!interaction.memberPermissions?.has(PermissionFlagsBits.ModerateMembers) && name !== "warn" && name !== "purge") {
        await interaction.reply({ content: "Missing permissions.", ephemeral: true });
        break;
      }
      await interaction.reply({ embeds: [embed("Action applied in this server.", name)] });
      break;

    default:
      await interaction.reply({ content: "Unhandled command.", ephemeral: true });
  }
}

async function handleCommand(message, name, args) {
  const fake = {
    commandName: name,
    options: { data: args ? [{ value: args }] : [] },
    user: message.author,
    guild: message.guild,
    client: message.client,
    memberPermissions: message.member?.permissions,
    reply: (payload) => message.channel.send(payload),
    isChatInputCommand: () => true,
  };
  await handleInteraction(fake, name, args);
}

client.login(TOKEN);
